backend:
  name: gitlab
  repo: benaiah/netlify-cms-test-repo

collections:
  - create: true
    fields:
      - label: Title
        name: title
        widget: string
      - collection: authors
        label: Author
        name: author
        searchFields:
          - title
        valueField: title
        widget: relation
      - label: Body
        name: body
        widget: markdown
    folder: content/posts
    label: Posts
    name: posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  - create: true
    fields:
      - label: Name
        name: title
        widget: string
      - label: Description
        name: body
        widget: markdown
    folder: content/authors
    label: Authors
    name: authors
    slug: '{{slug}}'
  - name: file_collection
    label: "File Collection"
    delete: false
    editor:
      preview: false
    files:
      - name: "main"
        label: "Main"
        file: "content/file-collection.yml"
        description: "Main file collection"
        fields:
          - {label: "Site Title", name: "site_title", widget: "string"}
          - label: "Post Settings"
            name: posts
            widget: "object"
            fields:
              - {label: "Number of posts on frontpage", name: front_limit, widget: number}
              - {label: "Default Author", name: author, widget: string}
              - {label: "Default Thumbnail", name: thumb, widget: image, class: "thumb"}
media_folder: media
public_folder: content
publish_mode: simple
